# Generated by Django 4.0.3 on 2022-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('picture', models.ImageField(default='default value', upload_to='')),
                ('describe', models.TextField(default='DataFlair Django tutorials')),
            ],
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-author', 'title'], 'verbose_name': 'Мақала', 'verbose_name_plural': 'Мақалалар'},
        ),
    ]
