# Generated by Django 4.0.3 on 2022-04-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_mosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Takyryp')),
                ('is_published', models.BooleanField(default=True, verbose_name='Wyggarylym')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
