# Generated by Django 4.0.3 on 2022-04-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_tosts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esim', models.CharField(default='', max_length=255, verbose_name='Esimi')),
                ('teg', models.TextField(blank=True, default='', verbose_name='Tegi')),
                ('age', models.IntegerField(default=18, verbose_name='Zhasy')),
                ('email', models.EmailField(blank=True, default='@gmail.com', max_length=254, verbose_name='Elektrondyk poshta')),
                ('image', models.ImageField(blank=True, default='default value', null=True, upload_to='user_gallery', verbose_name='3*4 suret')),
                ('slug', models.SlugField(default='', max_length=255, unique=True, verbose_name='URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='Kelisim')),
            ],
        ),
    ]
